omnibor/omnibor-rs

.gitignore
Cargo.toml
src/lib.rs

creating library package

---

.github/workflows/rust.yml

test both no_std and std in github workflow

---

.github/workflows/rust.yml
Cargo.toml
src/lib.rs

Definitely open to feedback on this!
Signed-off-by: Nell Shamrell <nells@microsoft.com>

allows full use of the standard library

---

Cargo.toml
src/lib.rs

move from base64 to hex for sha256

---

Cargo.toml
src/lib.rs

move from sha1_smol to sha1 package

---

src/lib.rs

code and tests for a GitBom struct that GitOids can be added to

---

src/lib.rs

This commit does a few different things:
- Fixes clippy lints, mostly by actually fixing them, although a couple are "fixed" with `#[allow(clippy::...)]` annotations so that we don't see the warnings anymore.
- Adds or clarifies existing comments both to better document the parts of the API, and to explain the functioning of the code better in places.
- Renames some variables for clarity. In particular, any `digest` local variable is renamed `digester`, and `Source::get_digest` is now `Source::get_digester`. This is intended to make clearer that the function returns the type which performs the digest operations, and does _not_ return the digest itself.
- Removes a couple of unnecessary allocations. Namely, 1) the logic for producing a bunch of futures for `GitOid` generation and then …

Add comments, fix clippy lints, other minor fixups

---

gitbom/Cargo.toml

update gitbom Cargo.toml to use the uploaded gitoid crate

---

gitbom/Cargo.toml
gitbom/src/lib.rs
gitoid/Cargo.toml

increments version numbers prior to release

---

gitbom/Cargo.toml
gitoid/Cargo.toml

increments version numbers for release

---

gitbom/Cargo.toml
gitbom/src/lib.rs
gitoid/Cargo.toml
gitoid/src/builder.rs
gitoid/src/gitoid.rs
gitoid/src/tests.rs

Fixes #36 
Signed-off-by: Nell Shamrell <nells@microsoft.com>

removes async functionality

---

gitoid/Cargo.toml

increments crate version for gitoid

---

gitbom/Cargo.toml

updates gitbom to use new version of gitoid crate

---

gitoid/Cargo.toml

increments gitoid crate version number

---

README.md
gitoid/Makefile

re-ordering the gcc command to make it work on Ubuntu

---

gitbom/Cargo.toml

bumps gitbom crate dependency and version

---

.github/workflows/release.yml
Cargo.toml

Ran `cargo dist init`. Hopefully this is all correct!

feat: Setup `cargo-dist` to automatically deploy the `omnibor` tool.

---

omnibor/README.md

This commit adds an initial README for the `omnibor` package, which
encompasses both the OmniBOR library and binary crates.

chore: First pass at an OmniBOR package README

---

.github/workflows/test.yml
Cargo.toml
omnibor-cli/Cargo.toml
omnibor-cli/tests/snapshots/test__artifact_no_args.snap
omnibor-cli/tests/snapshots/test__debug_no_args.snap
omnibor-cli/tests/snapshots/test__manifest_no_args.snap
omnibor-cli/tests/snapshots/test__no_args.snap
omnibor-cli/tests/test.rs

Adds snapshot testing with 'cargo insta' for the CLI, to help catch future regressions in CLI output.
Fixes #134

feat: Add snapshot testing for CLI.

---

omnibor-cli/src/cmd/artifact/find.rs
omnibor-cli/src/fs.rs

This parallelizes 'artifact find' in the same way 'artifact id' has already been parallelized.

feat: Parallelize 'artifact find'

---

omnibor-cli/Cargo.toml
omnibor-cli/src/cmd/debug/paths.rs
omnibor-cli/src/print/error.rs
omnibor-cli/src/print/find_file.rs
omnibor-cli/src/print/id_file.rs
omnibor-cli/src/print/paths.rs

This adds basic support for color output for commands.

feat: Added color output

---

omnibor-cli/src/cmd/manifest/create.rs
omnibor-cli/src/config.rs
omnibor-cli/src/main.rs

This cleans up and improves logic for error reporting, including making sure that full error chains get printed.

feat: Improve error reporting.

---

omnibor-cli/src/cli.rs
omnibor-cli/src/cmd/artifact/id.rs
omnibor-cli/src/cmd/manifest/add.rs
omnibor-cli/src/cmd/manifest/mod.rs
omnibor-cli/src/cmd/manifest/remove.rs
omnibor-cli/src/cmd/mod.rs
omnibor-cli/src/cmd/store/add.rs
omnibor-cli/src/cmd/store/log.rs
omnibor-cli/src/cmd/store/mod.rs
omnibor-cli/src/cmd/store/remove.rs
omnibor-cli/src/fs.rs
omnibor-cli/src/main.rs
omnibor-cli/tests/snapshots/test__artifact_no_args.snap
omnibor-cli/tests/snapshots/test__debug_no_args.snap
omnibor-cli/tests/snapshots/test__manifest_no_args.snap
omnibor-cli/tests/snapshots/test__no_args.snap

This introduces a new "store" subcommand to handle modification of the file system store, and moves some of the planned functionality from the "manifest" subcommand to "store".

feat: Introduce new "store" subcommand.

---

omnibor/src/lib.rs

This updates the main documentation page with a list of goals to complete before releasing version 1.0.0 of this crate.
It's great to think we're getting closer and more stable! I think embedding is the one major technical hurdle remaining, and besides that it's a number of smaller mechanical things to fully expose our API to other languages via FFI, to enable complete cryptography library flexibility, and to fully document the APIs in the crate.

chore: More documentation.
