omnibor/omnibor-rs

.github/workflows/rust.yml, README.md
[Clippy](https://github.com/rust-lang/rust-clippy) is a very useful Rust linting tool to keep the code consistent and readable (especially as new contributors join). This pull request adds Clippy to our CI so that it will run on every PR.
=> Add clippy

Cargo.toml, src/lib.rs
This refactors the generation of gitoids, making it easier to add support for different hashing algorithms when we want to move beyond SHA1. I've also added some experimental support for SHA256 to demonstrate the ability to use different hashing algorithms.
=> Refactor and add sha256

src/lib.rs
Updated the code to support sorting and de-duping of `GitOid`s
Moved from using `String` to store `GitOids` to storing in the `GitOid` data structure itself. The advantage being well typed code as well as a data structure that supports `Copy` (byte copying) in addition to `Clone`.
=> Sorting, de-duping, and GitOid structs

Cargo.toml, src/lib.rs
Created a `const` for the size of the hash byte array. If we add a new hash algorithm that has a hash size greater than 32 bytes,
we can update the const to support the larger value.
Also, added `async` methods for generating a bunch of `GitOid`s
Signed-off-by: David Pollak <feeder.of.the.bears@gmail.com>
=> Created a `const` for size of byte array that holds the hash

gitbom/Cargo.toml, gitoid/Cargo.toml
gitbom already exists on crates.io as version 0.1.0.
We have made some significant changes to it. I have incremented the version number to 0.1.1. Although normally changes of this nature would require a major version increase, we are still pre-1.0.
Per the [semver spec](https://semver.org/):
```
Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable
```
I would also like to keep the gitoid version number in sync with the gitbom version number for as long as possible. Therefore, I am starting that version number at 0.1.1 as well.
=> synchronizes version numbers

gitbom/Cargo.toml, gitbom/src/lib.rs, gitoid/Cargo.toml, gitoid/src/builder.rs, gitoid/src/error.rs, gitoid/src/gitoid.rs, gitoid/src/hash_algorithm.rs, gitoid/src/lib.rs, gitoid/src/object_type.rs, gitoid/src/tests.rs
These commits do a few things.
1. Bump the dependency versions to their latest.
2. Introduce an `ObjectType` enum and make it a parameter of all the `GitOid` constructors.
3. Rename the `HashAlgorithm` variants to `Sha1` and `Sha256`, so the capitalization matches regular Rust style.
4. Introduce a `GitOidBuilder` type to make constructing many `GitOid`s with the same configuration easier.
5. Modify the trait bound on `GitOid::new_from_reader` from `BufReader<R>: Read` to `R: Read`.
On the second item: for the `gitbom` crate I believe we only care about the `ObjectType::Blob` variant, but the `gitoid` crate might have other users who want to handle other types of Git objects.
On the builder, this is the simplest-possible builder at the moment; the configuration is only set in the …
=> Further GitOid improvements

gitoid/src/gitoid.rs, gitoid/src/hash.rs, gitoid/src/lib.rs, gitoid/src/tests.rs
This is intended to make the API clearer in separating the hash, which is part of the `GitOid` but not sufficient for representing the `GitOid`, from the overall `GitOid` structure. The `GitOid` can be represented as a URI, or you can extract the parts (hash algorithm, object type, hash) individually. If you have the `Hash`, now represented as a struct, you can either access the individual bytes through the `Deref` impl or `as_bytes` method, or you can get the hexadecimal encoding through the `Display` impl or the implied `to_string` method or explicit `hex` method.
=> Introduce a separate Hash struct.

gitoid/src/error.rs, gitoid/src/gitoid.rs, gitoid/src/hash_algorithm.rs, gitoid/src/object_type.rs, gitoid/src/tests.rs
This commit adds the ability to try to construct a `GitOid` from a `url::Url` by parsing the parts of the `Url` to ensure they contain all the required data, and then constructing a `GitOid` if they do.
This includes additions to enable parsing `ObjectType` and `HashAlgorithm` from a string slice, plus new error variants (with either `String` or `Box<Url>` fields) to represent different modes of failure for parsing.
This commit also renames `GitOid::uri` to `GitOid::url`.
The new name is a more-specific explanation of what we're dealing with, and matches the type returned (`url::Url`). This change also makes `GitOid::url` consistent with `GitOid::new_from_url`. I also added new tests to validate that the correct errors are produced for different types of invalid `Url`s.
Signed-off-by: …
=> Add `GitOid::new_from_url` and `TryFrom`.

gitoid/src/builder.rs, gitoid/src/ffi/gitoid.rs, gitoid/src/finder.rs, gitoid/src/gitoid.rs, gitoid/src/lib.rs, gitoid/src/tests.rs
This commits adds a new `Finder` struct which matches different sources of `GitOid`s against a known set of `GitOid`s, returning both an identifier and the matching `GitOid` itself, along with reporting any errors that arise when resolving the new `GitOid`s.
The docs for the `Finder` struct spell it out the clearest. This design is centered around the new `IntoIdentifiedGitOid` trait, which is implemented for a variety of existing types. The goal of this is to allow the `Finder` to be generic over things which produce `GitOid`s, so that, for example, someone could add a mechanism to resolve `GitOid`s from a `Url` without changing any existing code.
=> First draft of a finder implementation

README.md
This change does a couple of things:
- Rewrites the README to no longer include any references to GitBOM, and instead use the new OmniBOR name throughout.
- Adds new sections for the license and contributing information.
- Simplifies the "use from other languages" information, and removes the "adding `NUM_HASH_BYTES`" material which, as far as I can tell, is no longer required (at least, running `cbindgen` on the hosts I have on hand always include `NUM_HASH_BYTES` automatically).
- More generally, rewrites the language to be clearer about what this project is and what benefits it is intended to offer in the software supply chain space.
__Edit__: [Rendered](https://github.com/omnibor/omnibor-rs/blob/8ca4c661793366251df3b9fd732d2c841d71f1bc/README.md)
=> Rewrite README for clarity and project rename.

gitoid/Cargo.toml, gitoid/src/error.rs, gitoid/src/ffi/error.rs, gitoid/src/ffi/gitoid.rs, gitoid/src/ffi/util.rs, gitoid/src/gitoid.rs, gitoid/src/hash_algorithm.rs, gitoid/src/hash_ref.rs, gitoid/src/object_type.rs
=> Initial steps toward making `std` an optional feature.

gitoid/src/ffi/gitoid.rs, gitoid/src/gitoid.rs
Previously we required buffering when constructing a GitOid
from a file, but this isn't always desirable. This commit makes
the API generic over any reader, and also updates the FFI to
make buffering optional.
Closes #79
=> feat: Remove BufReader req for GitOid construction

gitoid/src/ffi/gitoid.rs, gitoid/src/gitoid.rs, gitoid/src/tests.rs
This commit shortens constructor names to make code a little easier to parse visually.
=> Shortened GitOid constructor names.

omnibor/Cargo.toml, omnibor/src/lib.rs
This initial commit just defines an artifact ID type that selects
the specific construct of the GitOid type.
=> Implement ArtifactID type.

gitoid/src/ffi/mod.rs, gitoid/src/gitoid.rs, gitoid/src/lib.rs
This commit rewrites the introductory docs for the crate,
and also reorganizes some docs for FFI and hashes slightly
to be clearer / cleaner. FFI is no longer marked doc(hidden),
and the contents of crate::ffi::gitoid have been re-exported
to appear under crate::ffi directly. This isn't _really_ that
important since they're only intended to be called from C
code anyway, but at least this way they appear in the Rust
docs and are easier to find.
=> feat: rewrite docs intro, reorg docs slightly

gitoid/Cargo.toml, gitoid/src/ffi/gitoid.rs, gitoid/src/gitoid.rs, gitoid/src/hash_algorithm.rs, gitoid/src/lib.rs, gitoid/test/c/test.c
This commit does a few things:
- Refactors gitoid_from_buffer to delegate to BufReader.
- Uses format_bytes::format_bytes instead of format to construct
prefix for hashing.
- Adds GitOid::from_reader_with_expected_length to support
non-Seek-able readers and avoid cost of seeking if length is
already known.
- Adds GITOID_URL_SCHEME constant to replace two uses of
literal string and ensure they're always consistent.
- Updates FFI to support new from_reader_with_expected_length
- Updates FFI to avoid double-buffering when building a GitOid
from a reader, since the underlying implementation buffers.
- Adds FFI support for new from_reader_with_expected_length
constructor.
- Renames FFI constructor from _new_from_* to _from_*, and
updates C test code to use the new prefix.
=> feat: improved gitoid_from_buffer, misc. fixups

README.md, gitoid/README.md, omnibor/README.md
This commit rewrites the README to more clearly explain
the background and goals of OmniBOR and of the Rust
implementation.
Right now it delegates info to crate-specific
READMEs which haven't been written yet. So there's more
work to do prior to merge. We also
need to at least publish a placeholder omnibor crate to crates.io.
=> feat: first draft of README rewrite

gitoid/src/gitoid.rs
Turns out the prior bounds were more complicated than
they needed to be. H::OutputSize works instead of
<H as OutputSizeUser>::OutputSize.
=> feat: Simplify GitOid trait bounds

gitoid/src/ffi/gitoid.rs
Haha this is why we need Windows CI jobs. A prior
commit missed updating two function calls in the
Windows FFI code, causing compilation issues. This
commit fixes it.
=> fix: Fixed broken FFI code on Windows.

gitoid/src/ffi/gitoid.rs
Another commit fixing a Windows-specific issue. This
time that the BufReader import was removed, and Unix
uses of it in the FFI code were removed, but not for
Windows code, causing compilation failure on Windows.
This commit fixes the issue.
=> fix: Windows FFI mistakenly using BufReader

gitoid/Cargo.toml, gitoid/src/gitoid.rs
This commits adds two new constructors for `GitOid` to build new
GitOIDs from async readers, with or without an expected length
being provided.
This was pretty easy! I've generally stayed away from doing async
things because of the general vibe that it's kinda finicky / difficult.
I'm happy this was so simple to do.
=> feat: Add async constructors for GitOid.

gitoid/src/lib.rs, gitoid/src/object_type.rs
This commit adds a top-level example to the crate docs, and also fixes
a broken link in the docs for ObjectType.
=> feat: add top-level docs example.

gitoid/src/lib.rs, omnibor/Cargo.toml, omnibor/src/artifact_id.rs, omnibor/src/error.rs, omnibor/src/lib.rs, omnibor/src/sealed.rs, omnibor/src/supported_hash.rs
This commit completes the first implementation of the
ArtifactId type, which is really just a wrapper
around GitOid.
This includes all methods delegating to GitOid
under the hood, plus examples run as doc tests which
all pass!
=> Initial `omnibor::ArtifactId` implementation

omnibor/src/artifact_id.rs, omnibor/src/lib.rs
This commit does two things:
- Renames ArtifactId constructors from `from_*` to `id_*`, which
hopefully makes it more clear that the first parameter is the thing
being _identified_.
- Added further documentation for all public methods on [`ArtifactId`],
plus some documentation on the crate root.
=> feat: renamed ArtifactId methods and add docs

gitoid/src/gitoid.rs, gitoid/src/tests.rs
Previously the Display impl for GitOid printed some but not all of the
data associated with the URL representation. This commit changes that to
just print the URL representation, and updates the GitOid::url method
to delegate to `to_string` which delegates to that `Display` impl.
=> feat: make GitOid display print URL format

omnibor/Cargo.toml, omnibor/src/bin/omnibor.rs
This commit introduces a new, and currently very basic, OmniBOR CLI.
At the moment, this CLI is only able to produce Artifact Identifiers
for files it's given. In the future it'll be expanded with more
functionality.
To use the CLI during development, run:
cargo run --features="build-binary" -- <CLI ARGS>
Replace `<CLI ARGS>` with arguments for the CLI. Use the `--help` flag
to find out the API of the CLI.
=> feat: introduce new OmniBOR CLI.

omnibor/src/bin/omnibor.rs
This commit adds a --hash/-H flag to the CLI commands to support
specifying the underlying hash algorithm to use for IDs. Currently
only SHA-256 is supposed, but the OmniBOR spec is designed to handle
future changes to add other algorithms (for example, if SHA-256
is later broken and collisions become possible to generate).
It also mildly improves help text for the CLI.
=> feat: add --hash flag to CLI commands

omnibor/Cargo.toml, omnibor/src/bin/omnibor.rs
The prior logic unnecessarily recursed, in fact the underlying walker
handled recursion correctly already, and the code only needed to handle
skipping directories.
This commit also cleans up and simplifies the run_* functions' code by
pulling some things out into their own functions which report nice
error messages.
=> fix: Fix double-print in tree command.

omnibor/Cargo.toml, omnibor/src/bin/omnibor.rs
This commit combines the `id` and `tree` subcommands, and also adds a
new `find` subcommand. So there are two commands:
- `id`: If given a file, ID it. If given a directory, recursively ID
all files within it.
- `find`: Given a `gitoid` URL and a root directory, search under the
root dir to find a file that matches the `gitoid`.
This commit also cleans up the code a bit.
=> feat: Combine CLI id/tree cmds, add find cmd

Cargo.toml
This change is intended to make `cargo release` use a Conventional
Commit compatible prefix when committing new releases.
=> chore: Config cargo-release commit message.

gitoid/Cargo.toml, gitoid/README.md, omnibor/Cargo.toml
This commit includes a README for the `gitoid` crate which documents a
bit about what the crate is for and how it's designed. There's more to
add in the future, but it's a starting point.
This commit also replaces the current description of the `gitoid` crate
with a better one that should hopefully be clearer to users on
Crates.io.
=> docs: Add gitoid crate README, update crate desc.

omnibor/Cargo.toml, omnibor/src/bin/omnibor.rs
This commit implements asynchronous printing in the CLI by having a
printing task that handles all printing, and having other tasks just
send messages to say they want something printed. This ensures nothing
interleaves while doing async printing, and that printing doesn't block
the workers.
This commit also introduces a structured Msg type for what gets printed,
handling the different cases of stdout vs. stderr and plain vs. JSON
output.
=> feat: Implemented async printing in CLI

.cargo/config.toml, Cargo.toml, gitoid/Cargo.toml, omnibor/Cargo.toml, xtask/Cargo.toml, xtask/README.md, xtask/src/cli.rs, xtask/src/main.rs, xtask/src/pipeline.rs, xtask/src/release.rs
This commit implements the initial scaffolding of the 'cargo xtask'
pattern for the OmniBOR Rust workspace. In particular, it defines
logging, a basic CLI, a mechanism for pipelining and rollback of steps
in a process, and the rough outline of a "release" subcommand which
will in the future handle releasing new versions of crates in the
workspace.
=> feat: Add 'cargo xtask' for custom tasks

omnibor/Cargo.toml, omnibor/src/bin/omnibor.rs
Added an option to only print the gitoid in "plain" output mode so that it can be passed directly to `curl` or otherwise be used in CLI applications.
Also, ensured the print buffer (an async thread) has completed outputting before the program is terminated. This addressed a bug when using `curl https://goatrodeo.org/omnibor/$(omnibor id ...)`
Okay... I'm being bad. I didn't create an issue.
Make the tool CLI friendly
Smoke test
=> Ensured the print buffer is flushed before program exit, short printing

omnibor/src/bin/omnibor/find.rs, omnibor/src/bin/omnibor/main.rs, omnibor/src/bin/omnibor/print.rs
This commit just makes some small fixes in the CLI code, nothing
impacting behavior at all.
=> chore: Small fixups in the CLI code.

omnibor/src/bin/omnibor/find.rs, omnibor/src/bin/omnibor/print.rs
Previously, the 'short' format on the 'find' command would actually
just re-print the hash that was provided, as it was treating the
output identically to the `id` command. This commit introduces a new
`Msg` constructor for the `find` version, which is identical to the
`id` version for the `plain` and `json` formats, but which _only_
prints the found path in the 'short' format.
It also slightly refactors printing in `Msg` to avoid the trait object
and instead just match on the message status to decide where to write.
Signed-off-by: GitHub <noreply@github.com>
=> fix: Fix 'find' command short format.

omnibor/Cargo.toml, omnibor/src/lib.rs, omnibor/src/test.rs
This commit adds a new test for the ArtifactId<Sha256> type to ensure
the size of the ID is exactly the size of the buffer needed for the
SHA-256 hash, and nothing more.
=> feat: Add size test for ArtifactId<Sha256>

omnibor/src/bin/omnibor/find.rs
Previously, we'd incorrectly return, and therefore stop looking, when
a match was found in the 'find' command. This misses that there may be
duplicate files, and we want to report all of them.
This commit just removes the return, so we now keep searching and
report all matches.
=> fix: Don't stop looking at first 'find' match

omnibor/Cargo.toml, omnibor/src/artifact_id.rs, omnibor/src/bin/omnibor/find.rs, omnibor/src/error.rs, omnibor/src/test.rs
This commit adds an optional "serde" feature to the `omnibor` library
crate which implements `serde::Serialize` and `serde::Deserialize`
for `ArtifactId` if enabled. It also adds a test with the `serde_test`
crate to validate that it serializes as expected and roundtrips
back to the original value correctly.
This commit also cleans up some constructor names and modifies some
trait impls for correctness. In particular `FromStr` now performs
`Url::parse` followed by `ArtifactId::try_from_url` instead of running
`ArtifactId::id_str`, as this seems less surprising than hashing the
provided string.
=> feat: Optionally-implement serde for ArtifactId

gitoid/Cargo.toml, gitoid/src/gitoid.rs, gitoid/src/tests.rs
This commit makes it possible to serialize and deserialize `GitOid`s
to and from their URL representation. So they get serialized as
URLs and deserialized from URLs.
=> feat: Added 'serde' feature to `gitoid` crate

SECURITY.md
Decided that it made more sense to just list the crates the policy
applies to, rather than committing with such high specificity about
which versions of each crate will receive security updates. Things are
still evolving frequently enough that such a commitment doesn't make
sense for us.
=> chore: Update security policy.

xtask/src/pipeline.rs, xtask/src/release.rs
This commit corrects a bug where rollback would start undoing steps
from the beginning, rather than from the last-failed step.
Also generally polished the release code.
=> fix: correct rollback order, polish release flow

xtask/src/release.rs
This commit adds the final step of the `cargo xtask release` subcommand:
actually releasing the crate! Everything prior involves validating the
environment or checking the changelog, but the final step actually
publishes a new version. It still needs to be tested from a deployment
machine, but this should be pretty close!
=> feat(xtask): Implemented final 'release' step.

xtask/src/release.rs
For the version comparison against what's expected by `git-cliff`, we
have to do some version string parsing, and this involves stripping
a prefix off which specifies the crate to _only_ get the actual
version number triple portion. The prior prefix used was missing the
letter "v" which is part of the prefix, and so parsing failed in
practice. This commit adds the missing part of the prefix.
=> fix(xtask): Correct version prefix to include 'v'

xtask/src/release.rs
Previously, in the "commit-changelog" step of the `cargo xtask release`
command, we'd wrap the commit message in quotes. Turns out this is
processed by Git in a way that means the actual commit message header
is committed wrapped in quotes, which means it won't parse as a
conventional commit, and also that it breaks rollback (because
rollback checks commit messages to ensure it doesn't actually un-commit
the wrong thing).
This commit removes the quote wrapping, which should ensure correct
parsing _and_ avoid broken rollback.
=> fix(xtask): Don't quote CHANGELOG commit message.

xtask/src/release.rs
Previously, when rolling back the creation of the CHANGELOG file, we
would error out if the file couldn't be found for deletion. However,
if the commitment step afterward runs and gets rolled back, it will
un-commit and thereby delete the file anyway, so we can instead use
`rm -f` to _not_ error out if the file has already been deleted.
=> fix(xtask): Ignore missing files on rollback

xtask/src/main.rs
This modifies the construction of the logger to enable use of colors
again! Instead of writing our own custom formatter, this just modifies
configuration of the default formatter to not include information we
don't care about.
=> chore(xtask): Improve xtask logging format.

README.md
We don't currently commit to an MSRV, and it's good to be explicit
about that and recommend that users of the crate track Rust stable
versions.
In the future, it would be good to have MSRVs for the `gitoid` crate,
`omnibor` library crate, and `omnibor` binary crate separately.
=> chore: Document MSRV policy.

xtask/src/release.rs
This fixes a bug where the `release` task would try to prompt the user
to confirm, and then fail (without rollback happening) because it's
actually running in a non-interactive context.
This _does_ mean that when `--execute` is passed, it will really
publish a new version! So take care.
=> fix(xtask): Pass `--no-confirm` to `cargo-release`

xtask/src/release.rs
`xshell` uses some custom escaping logic under the hood that meant
trying to pass two args in a single string didn't work (they end up
as one quoted single arg, which `cargo-release` doesn't accept).
This commit modifies the flag inclusion logic to instead pass them
as a slice, which should expand correctly.
=> fix(xtask): Fix `execute` flag escaping.

xtask/Cargo.toml, xtask/src/release.rs
Previously, `cargo-release` being run in the sub-shell wasn't picking
up Cargo's authentication information, even if you'd previously run
'cargo login' to authenticate with the Crates.io registry. This commit
is intended to fix that by manually extracting the saved token from
Cargo's credentials file and passing it into the subshell using an
environment variable.
With how `xshell` works, this environment variable won't be logged
anywhere, so it's safe to pass the authentication token this way.
=> feat(xtask): Make `release` pickup Cargo creds.

xtask/src/release.rs
This commit refactors the extraction logic for the Cargo authentication
token to be clearer. It's still not working in my own testing, so I'll
have to continue tinkering with it.
=> fix(xtask): Refactor Cargo auth token extraction

xtask/src/release.rs
This commit updates how `git-cliff` is called in the
`cargo xtask release` subcommand, to make sure it's called with the
`--bump` flag so that further changes are marked as being part of the
next version instead of being "Unreleased".
=> fix(xtask): Call `git-cliff` with `--bump`

gitoid/src/gitoid.rs, gitoid/src/tests.rs
This commit modifies the method names for a number of `GitOid` methods
to clarify when the thing being passed in is being _hashed_ (any of the
`id_*` methods) vs. when it's being used as an identity itself to
construct a `GitOid` from `try_from_url`.
This should hopefully make it clearer how to _use_ the `GitOid` type
correctly!
This commit also modifies the `FromStr` implementation to use
`try_from_url` under the hood instead of `id_str`, as it seems
surprising to think that `FromStr` would actually be hashing the
contents to produce an identifier rather than being a convenient
shorthand for first parsing and then constructing from a
`gitoid`-scheme URL.
=> feat(gitoid): Rename `GitOid` methods for clarity

omnibor/Cargo.toml, omnibor/src/artifact_id.rs
This commit bumps our dependency on the `gitoid` crate from version
`0.5.0` to version `0.7.0`. To accomplish this, it:
- Modifies our serialization and deserialization logic for `ArtifactId`
to delegate to the implementation on `gitoid::GitOid`
- Updates constructor calls to use the new names that changed between
versions
- Updates the feature configuration of the `gitoid` dependency to no
longer use `sha1` or `sha1cd` at all, reducing the number of total
dependencies we need to import.
=> chore(omnibor): Bump `gitoid`: 0.5.0 -> 0.7.0

omnibor/Cargo.toml
This commit updates the `omnibor` package's configuration for
`cargo-dist` to specifically tell it to build the OmniBOR CLI using
the `"build-binary"` feature which it requires.
Huge thanks to @gankra for the guidance on how to do this!
=> chore(omnibor): Teach `cargo-dist` to build CLI

omnibor-cli/src/print.rs, xtask/src/cli.rs, xtask/src/release.rs
This commit updates how version parsing is done in
`cargo xtask release` to properly handle the new `omnibor-cli` crate.
It also adds an `--allow-dirty` flag to make it possible to iterate
on debugging the `release` task without having to first commit every
little edit. This flag, when active, just causes the `check-git-ready`
step to log a warning instead of erroring out if Git's worktree or
staging area are dirty.
=> fix(xtask): Fix broken version parsing in release

omnibor/Cargo.toml, omnibor/README.md
This commit rewrites the `README.md` file for the `omnibor` crate to
more clearly introduce OmniBOR and give clearer instructions for using,
testing, and contributing.
=> chore(omnibor): Improve `omnibor/README.md`

omnibor-cli/Cargo.toml, omnibor-cli/src/id.rs, omnibor-cli/src/main.rs, omnibor-cli/src/print.rs
This commit updates the async printing logic to fallback to printing
synchronously if async printing fails for some reason. If _both_ fail,
then it'll panic.
=> feat(cli): Fallback to sync printing if needed.

omnibor-cli/README.md
This commit updates the `README.md` for the OmniBOR CLI to more
clearly explain how to install the tool, and to generally look nicer.
=> chore(cli): Update `omnibor-cli/README.md`

.github/workflows/release.yml, Cargo.toml
This change updates the cargo-dist version and then enables the Github Artifact Attestations feature
=> feat(dist): udpate to 0.16, enable github attestations

.github/workflows/ci.yml, gitoid/Cargo.toml, gitoid/README.md, gitoid/benches/benchmark.rs, gitoid/src/backend/boringssl.rs, gitoid/src/backend/mod.rs, gitoid/src/backend/rustcrypto.rs, gitoid/src/boring_sha.rs, gitoid/src/hash_algorithm.rs, gitoid/src/lib.rs, gitoid/src/tests.rs
This commit introduces support for the BoringSSL backend for SHA-1 and
SHA-256 in the gitoid Rust package. The SHA-1CD algorithm is not
supported with this backend. To enable BoringSSL, use the "boring"
feature in Cargo.
Additionally, benchmarks have been added to measure the performance
of the implemented cryptographic algorithms.
=> feat(gitoid): Add BoringSSL backend support for SHA-1 and SHA-256 in gitoid

gitoid/Cargo.toml, gitoid/src/gitoid.rs, gitoid/src/lib.rs
This commit includes some minor formatting fixes, addition of comments to
the Cargo.toml for the gitoid crate, and adjustment of some conditional
compilations to ensure that we can still compile in some specific
combinations of features which were accidentally made failing by some
prior changes.
=> chore: Add comments, fixup conditional compilations

omnibor-cli/src/cmd/artifact/find.rs, omnibor-cli/src/cmd/artifact/id.rs, omnibor-cli/src/cmd/debug/config.rs, omnibor-cli/src/cmd/manifest/add.rs, omnibor-cli/src/cmd/manifest/create.rs, omnibor-cli/src/cmd/manifest/remove.rs, omnibor-cli/src/fs.rs, omnibor-cli/src/main.rs, omnibor-cli/src/print/mod.rs
Wrap the underlying Tokio sender so we can do our own error type on it. This updates all callers to only use the new wrapper type.
=> feat: Introduce PrintSender type

.cargo/config.toml, omnibor-cli/Cargo.toml, omnibor-cli/src/error.rs, omnibor-cli/src/fs.rs, omnibor-cli/src/main.rs, omnibor-cli/src/print/mod.rs
Update the ID logic to work in parallel, with a "walk task" that walks the directory structure, and a dynamic set of "worker tasks" that consume the paths produced by the walk task and ID each path.
This uses `async-channel` for its consume-once semantics.
=> feat: Identify files in parallel.

omnibor-cli/tests/data/main.c, omnibor-cli/tests/snapshots/test__artifact_id_json.snap, omnibor-cli/tests/snapshots/test__artifact_id_plain.snap, omnibor-cli/tests/snapshots/test__artifact_id_short.snap, omnibor-cli/tests/test.rs
This adds snapshot tests for all three formats of the `omnibor artifact id` subcommand, to catch formatting regressions in the future.
=> feat: Added snapshot tests for `omnibor artifact id`

omnibor-cli/src/cli.rs, omnibor-cli/src/main.rs, omnibor-cli/tests/snapshots/test__artifact_no_args.snap, omnibor-cli/tests/snapshots/test__debug_no_args.snap, omnibor-cli/tests/snapshots/test__manifest_no_args.snap, omnibor-cli/tests/snapshots/test__no_args.snap
I have a more general plan for handling performance tunables that doesn't involve adding a bunch of one-off command line flags.
=> chore: Remove "buffer" tunable.

omnibor-cli/Cargo.toml, omnibor-cli/config/omnibor.json, omnibor-cli/src/app.rs, omnibor-cli/src/cli.rs, omnibor-cli/src/cmd/artifact/find.rs, omnibor-cli/src/cmd/artifact/id.rs, omnibor-cli/src/cmd/debug/config.rs, omnibor-cli/src/cmd/manifest/add.rs, omnibor-cli/src/cmd/manifest/create.rs, omnibor-cli/src/cmd/manifest/remove.rs, omnibor-cli/src/config.rs, omnibor-cli/src/error.rs, omnibor-cli/src/fs.rs, omnibor-cli/src/log.rs, omnibor-cli/src/main.rs, omnibor-cli/tests/snapshots/test__artifact_no_args.snap, omnibor-cli/tests/snapshots/test__debug_no_args.snap, omnibor-cli/tests/snapshots/test__manifest_no_args.snap, omnibor-cli/tests/snapshots/test__no_args.snap
This introduces an optional config file which permits the user to tune the operation of the CLI. For now this is just parameters related to Tokio runtime execution; there may be more options in the future.
=> feat: Introduce config for tunables

.gitattributes, gitoid/Cargo.toml, gitoid/src/backend/boringssl.rs, gitoid/src/backend/openssl.rs, gitoid/src/backend/rustcrypto.rs, gitoid/src/error.rs, gitoid/src/gitoid.rs, gitoid/src/gitoid_url_parser.rs, gitoid/src/hash_algorithm.rs, gitoid/src/internal.rs, gitoid/src/lib.rs, gitoid/src/object_type.rs, gitoid/src/tests.rs, gitoid/src/util/for_each_buf_fill.rs, gitoid/src/util/mod.rs, gitoid/src/util/stream_len.rs, gitoid/test/data/unix_line.txt, gitoid/test/data/windows_line.txt, omnibor-cli/tests/snapshots/test__artifact_id_json.snap, omnibor-cli/tests/snapshots/test__artifact_id_plain.snap, omnibor-cli/tests/snapshots/test__artifact_id_short.snap, omnibor-cli/tests/test.rs, omnibor/src/artifact_id.rs, xtask/Cargo.toml
This should ensure consistent Artifact IDs whether on Windows or Unix systems.
=> feat: Implement newline normalization.

omnibor/Cargo.toml, omnibor/src/hash_provider/boringssl.rs, omnibor/src/hash_provider/openssl.rs, omnibor/src/hash_provider/rustcrypto.rs, omnibor/src/lib.rs
Some parts of our API rely on features being turned on, and it would be good to show that fact on Docs.rs.
=> chore: Make Docs.rs show feature annotations.

omnibor/Cargo.toml, omnibor/src/storage/file_system_storage.rs
Technically `tracing` had two use sites, but neither was particularly useful. I'm happy to put `tracing` back in sometime in the future when I can go through the crate and make sure we're being consistent about when and how we do logging.
=> chore: Removed unused dependencies.

.github/workflows/release.yml, .github/workflows/test.yml, dist-workspace.toml
This upgrades 'dist' (formerly called 'cargo-dist') to 0.28.0, and updates our CI testing config to essentially match the hosts 'dist' uses for a release. We do additionally test on macos-14 to validate Apple Silicon support, whereas 'dist' does cross-compilation from macos-13 instead.
=> chore: Upgrade 'dist'

.github/workflows/release.yml, dist-workspace.toml
GitHub has deprecated support for Ubuntu 20.04 on the free tier, so we need to upgrade to use 22.04.
=> chore!: Update Ubuntu runners to 22.04.

.github/workflows/test.yml
This amends the list of CI runners for test jobs to use Ubuntu 22.04, since GitHub has sunset 20.04. This also syncs the runners between test and release, with release runners managed by `dist`.
=> chore!: Sync test runners w/ release runners.
